language: java
sudo: false
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
before_install:
- export TZ=Australia/Canberra
- date
- mkdir -p ~/.m2
- wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./mvnw deploy -DskipTests=true'
env:
  global:
  - secure: Z45y9zN9PXsLePWSOZ07rOY2Vz1GlJwIDIuLoqaeul9C+TMeK5TLzV5nXQUqraimQDS1nW1fYeyoltyP/pa1VNk2O9T8Zfs+2SrE17ftN1821rmPf3UFsofKmrocCuOPs91qdmmpUvlA8XA+NZNBJAdjRCTPNNBVzuPFXNrjc1CICcu1hfUr6Sh4owIOsSSyRNdk6v+Id/ibWxrh2SiTSVR4t4Poqd31g2daA66LqLNS/taGCjQ1NYjgRFSLfK4GP48amrQrLPBc5zoHyK518JVoAQwvNTWo0Z2m0/jeyZlpPEuA8SQi1GcECZIwr/HMrtzf5mwTG+0IOmGG+TuHs1x9QewVoBSlkARz5BjvwGLiJJ9vmQnFdR0acLrxm207h6Ks7Q467E/FtJFftsmHr4ThKmHPHZtknJqKoZ0n1+jTkGh8X25oq+/D3QzdtXgwlf3bYBV8UXrpI6L/FE+Abqzlt7EmSMTRZJlhybyg8rGfMqSmhDjmvjy5fRKubEKL2aGpqaQ5s1bBz3PmLKJEO3Oh210qJIVJJSQHaa2FZhJcjIqjU7mOD3bVaxqc51YaAzZ/8rj37J63DQTrAWJouVAw1kRYJdRacljBqbnb8kRKR7Nm3pQw4jUnFXIXQf+s3gh4AduDSHky7sT2oDEwyuYnypR9k7OeR8zT8KnpHYU=
  - secure: ULV0PBQa6UuEySh/OwNuhHumhwUi1kVYNPqFmhdw7d+S4imLQSHBskethUzj7DtjIYuANpBI8M5gDflUoXdD+v0wKldZa3V5R4GsL9o2UUp/5tgoXyNREetyqWs9YMpozhTTCe+E6pB/GPDBAwfbh6K/27V/kw+1nsRtJ0W8hlQbqGQaPhB04VoVhChHYpIJRjQwXuzAXnVjeSfF5gTMWUsS1nIaJVmV7YYyC+MXSxgB8a93PB50qcgOCxbkCE4Z7bVYJ8ck+m60hWso3gngpmOWt4JSojR2kuONKiRq45Ymz5dlal5jaxXSuoC3NmEjjcaZUwSJ+t+UKXPjKBsNDnAjOj0ev4VWKI+N3c6oFGeYz/qOgaYuvBHKfHTdBChTq9jLTBmM4KlPwV5xPOAtUUxY5OpmxZvExiKXIzTIA4CC9BEx5WLVlRBaBKFMOSoU34TUpjVEAd1AUci25ySmzQ5N7jeWXcGz6gqepKiMWkH2jTRZ8SIldL7jy+rg3Po/Mw+AXS2GAHBidJ0bEa59gleMbfxcZNmzlM2tGtfthiR/eg7WjyoeX5sdwnJ6fMjMl9V0qP2cntZNWPo8tlv9EImQW9B9UTvEvySFc3NPwTwSYXqOm+SYf+v+qwmi60Ag0ZtBJKH6TdLtljVW73Mi0gpx0usCsUdIXibNm9DPLkc=
